### PR TITLE
Upgrades to ios PhoneGap

### PR DESCRIPTION
**Pull request by genecyber**

### CODE REVIEW

**Comment by weilu** [comment]
@jsuder @haustraliaer Are most of the files in here generated files? Should they not be checked into source control?

**Comment by weilu** [comment]
@genecyber It's impossible to review. Can you highlight what are your changes and/or what are generated?

**Comment by genecyber** [comment]
These commits should probably go into a branch for a while. We might consider bumping the hive version. I upgraded phonegap and a few plugins. There were only a handful of new files added. Mostly existing files were modified. 

There is the ability to specify the plugins and versions in a config file and have the files downloaded upon build but this project was not set up that way. 

I also could not get the build scripts to build but the generated Xcode project built just fine. This implies that the build scripts might need to be updated.

**Comment by weilu** [comment]
> There were only a handful of new files added

What are they exactly? Did you add them or the upgrade added them? 

I'm only interested in the changes that you made by hand, not the generated files from the upgrade. 

> I also could not get the build scripts to build but the generated Xcode project built just fine.

What's the error you are seeing? If we can't re-generate the Xcode project how can you upgrade it without it being overwritten after we fix whatever issue you have with the build script?

**Pull request closed without merging**
